fix(ci): skip building agents
Signed-off-by: Jan Pokorný <JenomPokorny@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,69 +11,69 @@ permissions:
   id-token: write
 
 jobs:
-  agents:
-    runs-on: ubuntu-latest
-    environment: release
-    strategy:
-      matrix:
-        agent:
-          - chat
-          - rag
-          - form
-          - canvas
-    steps:
-      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
-      - id: version
-        run: |
-          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
-          echo "latestTag=$([[ ${GITHUB_REF#refs/tags/v} =~ [a-zA-Z] ]] && echo prerelease || echo latest)" >> $GITHUB_OUTPUT
-      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
-      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
-        with:
-          context: .
-          file: ./agents/${{ matrix.agent }}/Dockerfile
-          push: false
-          load: true
-          build-args: |
-            RELEASE_VERSION=${{ github.ref_name }}
-          tags: tmp-agent-image
-          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache
-          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache,mode=max
-      - id: agent-manifest
-        run: |
-          set -e
-          docker run -d --rm --name=tmp-agent -p 8000:8000 -e HOST=0.0.0.0 -e PORT=8000 tmp-agent-image
-          success=0
-          for i in {1..30}; do
-            echo "Extracting manifest: attempt $i"
-            response=$(curl http://localhost:8000/.well-known/agent-card.json 2>/dev/null) && success=1 && break
-            sleep 0.5
-          done
-          [[ "$success" == 1 ]] || (echo "Failed to discover agents" && exit 1)
-          docker kill tmp-agent
-          AGENT_MANIFEST=$(echo "$response" | base64 -w 0)
-          echo "content=$AGENT_MANIFEST" >> $GITHUB_OUTPUT
-      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
-        with:
-          context: .
-          file: ./agents/${{ matrix.agent }}/Dockerfile
-          push: true
-          platforms: linux/amd64,linux/arm64
-          build-args: |
-            RELEASE_VERSION=${{ github.ref_name }}
-          tags: |
-            ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:${{ github.sha }}
-            ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:${{ steps.version.outputs.version }}
-            ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:${{ steps.version.outputs.latestTag }}
-          labels: |
-            kagenti.dev.agent.json=${{ steps.agent-manifest.outputs.content }}
-          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache
-          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache,mode=max
+  # agents:
+  #   runs-on: ubuntu-latest
+  #   environment: release
+  #   strategy:
+  #     matrix:
+  #       agent:
+  #         - chat
+  #         - rag
+  #         - form
+  #         - canvas
+  #   steps:
+  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
+  #     - id: version
+  #       run: |
+  #         echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
+  #         echo "latestTag=$([[ ${GITHUB_REF#refs/tags/v} =~ [a-zA-Z] ]] && echo prerelease || echo latest)" >> $GITHUB_OUTPUT
+  #     - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
+  #     - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
+  #       with:
+  #         context: .
+  #         file: ./agents/${{ matrix.agent }}/Dockerfile
+  #         push: false
+  #         load: true
+  #         build-args: |
+  #           RELEASE_VERSION=${{ github.ref_name }}
+  #         tags: tmp-agent-image
+  #         cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache
+  #         cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache,mode=max
+  #     - id: agent-manifest
+  #       run: |
+  #         set -e
+  #         docker run -d --rm --name=tmp-agent -p 8000:8000 -e HOST=0.0.0.0 -e PORT=8000 tmp-agent-image
+  #         success=0
+  #         for i in {1..30}; do
+  #           echo "Extracting manifest: attempt $i"
+  #           response=$(curl http://localhost:8000/.well-known/agent-card.json 2>/dev/null) && success=1 && break
+  #           sleep 0.5
+  #         done
+  #         [[ "$success" == 1 ]] || (echo "Failed to discover agents" && exit 1)
+  #         docker kill tmp-agent
+  #         AGENT_MANIFEST=$(echo "$response" | base64 -w 0)
+  #         echo "content=$AGENT_MANIFEST" >> $GITHUB_OUTPUT
+  #     - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
+  #       with:
+  #         context: .
+  #         file: ./agents/${{ matrix.agent }}/Dockerfile
+  #         push: true
+  #         platforms: linux/amd64,linux/arm64
+  #         build-args: |
+  #           RELEASE_VERSION=${{ github.ref_name }}
+  #         tags: |
+  #           ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:${{ github.sha }}
+  #           ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:${{ steps.version.outputs.version }}
+  #           ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:${{ steps.version.outputs.latestTag }}
+  #         labels: |
+  #           kagenti.dev.agent.json=${{ steps.agent-manifest.outputs.content }}
+  #         cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache
+  #         cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/agents/${{ matrix.agent }}:cache,mode=max
 
   vm:
     environment: release
@@ -106,7 +106,9 @@ jobs:
             ${{ matrix.arch == 'x86_64' && format('apps/microshift-vm/dist/{0}/microshift-vm-{0}.wsl', matrix.arch) || '' }}
 
   adk:
-    needs: [agents, vm]
+    needs:
+      - vm
+      # - agents
     runs-on: ubuntu-latest
     environment: release
     env:
